In [ ]:
#TREATING MISSING VALUES.
# By default, missing values are represented with NaN, "not a number".
# WARNING: If your dataset has 0s, 99s, 0r 999s, be sure to either drop or approximate them as you would with missing values, otherwise you may end up with inaccurate results.

In [1]:
# Missin Values in Python
import numpy as np
import pandas as pd

from pandas import DataFrame

In [28]:
data = {'names': ['David', 'John', 'Jane', 'Smith', 'Emily', 'richard', 'Abraham'],
        'age': [25, 30, 22, 35, 28, np.nan, 40],
        'gender': ['Male', 'Male', 'Female', 'Male', 'Female', 'Male', np.nan],
        'rank': [2, 1, 4, 5, 3, 6, 7]}

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1]=np.nan
ranking_df.iloc[3:6,3]=np.nan
ranking_df.iloc[3,:]=np.nan
ranking_df

     names   age  gender  rank
0    David  25.0    Male   2.0
1     John  30.0    Male   1.0
2     Jane   NaN  Female   4.0
3      NaN   NaN     NaN   NaN
4    Emily   NaN  Female   NaN
5  richard   NaN    Male   NaN
6  Abraham  40.0     NaN   7.0

In [3]:
#true represents the value that is missing and false represents the value that is not missing.
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False   True   False   True
6  False  False    True  False

In [4]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True  False    True  False
6   True   True   False   True

In [5]:
# This is to find the missing values in the age column.
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2     Jane  NaN      F   4.0
3      NaN  NaN    NaN   NaN
4    Emily  NaN      F   NaN
5  richard  NaN      M   NaN

In [29]:
# This function fill missing values in a DataFrame with a specified value with a single value
ranking_df.fillna(0)

     names   age  gender  rank
0    David  25.0    Male   2.0
1     John  30.0    Male   1.0
2     Jane   0.0  Female   4.0
3        0   0.0       0   0.0
4    Emily   0.0  Female   0.0
5  richard   0.0    Male   0.0
6  Abraham  40.0       0   7.0

In [30]:
ranking_df.ffill()

     names   age  gender  rank
0    David  25.0    Male   2.0
1     John  30.0    Male   1.0
2     Jane  30.0  Female   4.0
3     Jane  30.0  Female   4.0
4    Emily  30.0  Female   4.0
5  richard  30.0    Male   4.0
6  Abraham  40.0    Male   7.0

In [31]:
ranking_df.bfill()

     names   age  gender  rank
0    David  25.0    Male   2.0
1     John  30.0    Male   1.0
2     Jane  40.0  Female   4.0
3    Emily  40.0  Female   7.0
4    Emily  40.0  Female   7.0
5  richard  40.0    Male   7.0
6  Abraham  40.0     NaN   7.0

In [15]:
ranking_df = ranking_df.apply(lambda col: col.interpolate(method='linear') if col.dtype in ['float64', 'int64'] else col)

In [32]:
# Convert back to float first, then format
ranking_df['age'] = ranking_df['age'].astype(float).map('{:.2f}'.format)
ranking_df['rank'] = ranking_df['rank'].astype(float).map('{:.2f}'.format)

ranking_df

     names    age  gender  rank
0    David  25.00    Male  2.00
1     John  30.00    Male  1.00
2     Jane    nan  Female  4.00
3      NaN    nan     NaN   nan
4    Emily    nan  Female   nan
5  richard    nan    Male   nan
6  Abraham  40.00     NaN  7.00

In [33]:
ranking_df.dropna()

     names    age  gender  rank
0    David  25.00    Male  2.00
1     John  30.00    Male  1.00
2     Jane    nan  Female  4.00
4    Emily    nan  Female   nan
5  richard    nan    Male   nan

In [34]:
ranking_df.dropna(how='all')

     names    age  gender  rank
0    David  25.00    Male  2.00
1     John  30.00    Male  1.00
2     Jane    nan  Female  4.00
3      NaN    nan     NaN   nan
4    Emily    nan  Female   nan
5  richard    nan    Male   nan
6  Abraham  40.00     NaN  7.00

In [35]:
ranking_df.dropna(axis=1)

     age  rank
0  25.00  2.00
1  30.00  1.00
2    nan  4.00
3    nan   nan
4    nan   nan
5    nan   nan
6  40.00  7.00

In [36]:
ranking_df.dropna(axis=0)

     names    age  gender  rank
0    David  25.00    Male  2.00
1     John  30.00    Male  1.00
2     Jane    nan  Female  4.00
4    Emily    nan  Female   nan
5  richard    nan    Male   nan