In [6]:
!pip install --upgrade pip
!pip install pandas

In [7]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [8]:
numbers_df = pd.DataFrame(np.arange(0,90,3).reshape(10,3), index=['row 1', 'row 2', 'row 3', 'row 4', 'row 5', 'row 6', 'row 7', 'row 8', 'row 9', 'row 10'], columns=['column 1', 'column 2', 'column 3'])

In [9]:
numbers_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [ ]:
# Example of simple indexing
numbers_df.iloc[0,1]

np.int64(3)

In [11]:
numbers_df.iloc[0,1]=20

In [12]:
numbers_df

        column 1  column 2  column 3
row 1          0        20         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

In [ ]:
# fancy indexing
numbers_df.iloc[[1,2,4],[1,2]]

       column 2  column 3
row 2        12        15
row 3        21        24
row 5        39        42

In [14]:
# Example of boolean indexing
mask = numbers_df > 30

In [ ]:
mask
#  Example of Boolean operators replace numbers with value.

        column 1  column 2  column 3
row 1      False     False     False
row 2      False     False     False
row 3      False     False     False
row 4      False     False      True
row 5       True      True      True
row 6       True      True      True
row 7       True      True      True
row 8       True      True      True
row 9       True      True      True
row 10      True      True      True

In [16]:
numbers_df[mask]

        column 1  column 2  column 3
row 1        NaN       NaN       NaN
row 2        NaN       NaN       NaN
row 3        NaN       NaN       NaN
row 4        NaN       NaN      33.0
row 5       36.0      39.0      42.0
row 6       45.0      48.0      51.0
row 7       54.0      57.0      60.0
row 8       63.0      66.0      69.0
row 9       72.0      75.0      78.0
row 10      81.0      84.0      87.0

In [18]:
numbers_df[numbers_df>30]=0

In [19]:
numbers_df

        column 1  column 2  column 3
row 1          0        20         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30         0
row 5          0         0         0
row 6          0         0         0
row 7          0         0         0
row 8          0         0         0
row 9          0         0         0
row 10         0         0         0

In [20]:
# How to Slice values from the DataFrame
numbers_df.iloc[2:6, 1:3]

       column 2  column 3
row 3        21        24
row 4        30         0
row 5         0         0
row 6         0         0