In [ ]:
#TREATING MISSING VALUES.
# By default, missing values are represented with NaN, "not a number".
# WARNING: If your dataset has 0s, 99s, 0r 999s, be sure to either drop or approximate them as you would with missing values, otherwise you may end up with inaccurate results.

In [1]:
# Missin Values in Python
import numpy as np
import pandas as pd

from pandas import DataFrame

In [2]:
data = {'names': ['David', 'John', 'Jane', 'Smith', 'Emily', 'richard', 'Abraham'],
        'age': [25, 30, 22, 35, 28, np.nan, 40],
        'gender': ['M', 'M', 'F', 'M', 'F', 'M', np.nan],
        'rank': [2, 1, 4, 5, 3, 6, 7]}

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1]=np.nan
ranking_df.iloc[3:6,3]=np.nan
ranking_df.iloc[3,:]=np.nan
ranking_df

     names   age gender  rank
0    David  25.0      M   2.0
1     John  30.0      M   1.0
2     Jane   NaN      F   4.0
3      NaN   NaN    NaN   NaN
4    Emily   NaN      F   NaN
5  richard   NaN      M   NaN
6  Abraham  40.0    NaN   7.0

In [ ]:
#true represents the value that is missing and false represents the value that is not missing.
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False   True   False   True
6  False  False    True  False

In [4]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True  False    True  False
6   True   True   False   True

In [ ]:
# This is to find the missing values in the age column.
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2     Jane  NaN      F   4.0
3      NaN  NaN    NaN   NaN
4    Emily  NaN      F   NaN
5  richard  NaN      M   NaN

In [7]:
# This function fill missing values in a DataFrame with a specified value with a single value
ranking_df.fillna(0)

     names   age gender  rank
0    David  25.0      M   2.0
1     John  30.0      M   1.0
2     Jane   0.0      F   4.0
3        0   0.0      0   0.0
4    Emily   0.0      F   0.0
5  richard   0.0      M   0.0
6  Abraham  40.0      0   7.0

In [8]:
ranking_df.fillna(method='pad')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'